cloudwan/gohan_webui

.vscode/settings.json, app/js/views/appView.js
Filter side menu list using schema metadata
Also added config for vscode
=> Filter side menu list using schema metadata

app/js/models/schemaModel.js, app/js/views/dialogView.js, app/js/views/tableView.js, package.json
Implemented async request based on promises.
=> Removed sync requests.

app/js/views/tableView.js
Sometimes YAML lib fails to convert object to YAML.
In that case, post may be failed.
In this commit, we add proper error hanlding on this.
=> YAML Dump error handling

app/js/models/schemaModel.js, app/js/views/dialogView.js, app/js/views/formsEditors/objectListEditor.js
Add ordering for object in list.
=> Create custom editor for object in list.

app/js/models/schemaModel.js, app/js/views/dialogView.js, app/js/views/formsEditors/validators.js
Added custom validators like ipv4, ipv6, ipv4mask, cidr, mac, uuid, port, hostname, uri and cidr-or-ipv4.
=> Added custom validators

app/js/views/formsEditors/listEditor.js
This fixes the bug creating parent item from child item
=> Fix event propagation in nested array type

.eslintrc, .hooks/pre-commit, installHooks.sh, package.json, webpack.config.js
=> Configuration eslint to react.

app/css/sass/main.scss, app/js/views/tableView.js, app/templates/table.html, wercker.yml
this also fixes bug with searching for strings following  '<a data-id=' pattern
=> Added case-sensitive sorting by viewable field name in TableView.

app/css/sass/main.scss, app/js/views/dialogView.js, app/js/views/formsEditors/template.js, package.json
Tweak form template & css, also add Sortable.js for drag & drop sort feature instead of jQuery UI
=> Tweak Form Layout

app/css/sass/main.scss, app/js/views/dialogView.js, app/js/views/formsEditors/listEditor.js, app/js/views/formsEditors/template.js, package.json
If it is object type, it changes to Tab UI. Also, removes drag &
drop UI for array, changes to simple click sort.
=> Changes to Tab UI for Object type

app/js/views/tableView.js
Currently, table view get updated even if we have
error response in API call. In this commit, we will wait
update from server to update table.
=> Wait server response in form call

app/js/models/schemaModel.js, app/js/routers/router.js, app/js/views/appView.js
Removed diplicated and unused code.
=> Refactoring appView.

app/css/sass/main.scss, app/js/models/userModel.js, app/js/views/appView.js, app/js/views/headerView.js, app/js/views/loginView.js, app/templates/header.html, app/templates/login.html, package.json, test/models/userModel.js
- switched to use sessionStorage instead of cookie
=> Implement tenant selector

app/js/models/schemaModel.js, app/js/views/tableView.js, app/templates/table.html
=> Added server side pagination in tableView.

app/config.json.sample, app/js/models/schemaCollection.js, app/js/models/schemaModel.js, app/js/views/appView.js, app/js/views/tableView.js, app/templates/table.html
@thayashi / @nati  Can you check this?
@thealmightyone Can you squash all commits to one?
=> Refactoring tableView to server side pagination, filtering and sorting.

app/css/sass/main.scss, app/js/views/detailView.js, app/js/views/tableView.js, app/templates/detail.html
Add `{wait: true}`, it was added in previous table view
Change
`event.stopPropagation() -> event.preventDefault()`
preventDefault is appropriate for this purpose.
=> Wait server response, fix event handling

app/js/views/detailView.js, app/js/views/dialogView.js
Focus name field on dialog open.
=> Allow extending detailView with custom tableView.

app/js/views/detailView.js, app/js/views/tableView.js
=> Fix problem with current target on click

app/css/sass/main.scss, app/js/views/errorView.js, app/templates/error.html
CSS Tweak
Changes to find response object (it depends on each xhr object)
Add message detail
Remove collection.unsetAuthData(), some request don't have collection object as parameter, also, It doesn't have to do auth reset here.
=> Tweak errorview

app/js/views/errorView.js
=> Fix Handling Response Object

app/js/models/schemaModel.js, app/js/views/tableView.js
Added possibility to set sort filter by makeCollection function and by tableView constructor.
=> Added possibility to set sort filter.

app/css/sass/main.scss, app/js/views/dialogView.js, app/js/views/formsEditors/template.js
* Add description like **Indicates required field**
* Fix error message position in case of nested form
=> Tweak Forms UI

app/js/models/schemaModel.js, app/js/views/dialogView.js, app/js/views/formsEditors/numberEditor.js
Now sends undefined, if data is empty string.
=> Changed parsing data before send to server.

app/js/app.js, app/js/views/formsEditors/selectEditor.js, package.json
This commit enables to filter select menu, it'd be helpful to find the right item when there are so many list items.
=> Add select form filter

app/js/views/tableView.js, app/templates/dataPopup.html
A tag is preferable for popover html
=> Fix popover html format

.babelrc, app/js/models/schemaModel.js, package.json, webpack.config.js
Before merge we need to check this on other browsers.
Support table http://kangax.github.io/compat-table/es6/
=> Removed compilation from es2015 to es5.

app/js/views/dialogView.js
This fixes js error which occurs in some minor timing.
=> Fix DialogView Error

app/js/views/tableView.js
This params gives flexibility to render custom tableview.
=> Add params to TableView render parameter

app/index.js, app/js/app.js, app/js/browserDetect.js
Added login screen error message.
=> Added supported browser detection.

app/js/views/dialogView.js
Change the timing of dialog size adjustment, change the size before showing. This is more courtesy way to show dialog.
=> Improve Dialog Showing

app/index.js
Fixes not updating index.js setting for UI update. It needed to remove deleted views.
=> Fix index.js export setting

app/css/sass/layout.scss, app/js/views/appView.js
Small tweaks for extend token message
=> Tweak Extend Token Message

app/css/sass/layout.scss, app/js/models/schemaModel.js, app/js/views/tableView.js, app/js/views/topView.js, app/templates/detail.html, app/templates/table.html
Support Multiple Deletion, inspired by @nati's PR.
=> Multiple Deletion of Resources

app/js/views/breadCrumbView.js, app/templates/breadcrumb.html
=> Fix Breadcrumb Escaping

.babelrc, package.json, webpack.config.js
Problem was with UglifyJs and es6.
This commit disables UglifyJs plugin and adds babel preset to babel for minification es6 code.
=> Fix problem with build.

package.json, src/auth/components/Login.test.jsx, src/auth/components/SelectTenant.jsx, src/auth/components/SelectTenant.test.jsx, src/error/ErrorActions.js, src/error/ErrorActions.test.js, src/error/errorReducer.test.js, src/routes/LocationActions.js, src/routes/LocationActions.test.js, src/routes/locationReducer.js, src/routes/locationReducer.test.js, src/schema/SchemaAction.test.js, src/schema/SchemaActions.js, src/schema/schemaReducer.js, src/schema/schemaReducer.test.js, test/helpers/material.js
=> [PoC] Added tests for schema reducer and schema actions.

package.json, src/DetailView/DetailActions.js, src/DetailView/detailActions.test.js, src/DetailView/detailReducer.js, src/DetailView/detailReducer.test.js, src/Dialog/Dialog.jsx, src/Dialog/dialogReducer.js, src/Dialog/dialogReducer.test.js, src/schema/SchemaAction.test.js
I ignored eslint warnings for Table.jsx file.
=> [PoC] Add tests for dialog and detail.

app/js/views/detailView.js, app/js/views/tableView.js
This commit fixes XSS for relation property name in TableView and DetailView.
=> Fix XSS of relation property name

css/sass/main.scss, src/TableView/TableView.jsx, src/app/App.jsx, src/components/Table/Table.jsx, src/components/Table/TablePaginationComponent.jsx
Disable focus-border when not using keyboard keys.
=> Style tableView pagination component.

src/TableView/TableActions.js, src/TableView/TableView.jsx, src/app/App.jsx, src/auth/Auth.jsx, src/auth/AuthActions.js, src/components/Table/Table.jsx, src/components/Table/TableRowComponent.jsx
Handle Network Errors when gohan is down.
Remove active toasts on successul login.
=> Add confirmation when deleting resources.

package.json, src/TableView/TableSelectors.js, src/TableView/TableSelectors.test.js, src/TableView/TableView.jsx, src/routes/createRoutes.js
Added selectors to table view for optimization render time.
=> Clean up TableView.

css/sass/main.scss, src/components/Table/TableRowComponent.jsx
Add minimum width to yaml object editor.
=> Add code editor within popover to Table View.

app/js/models/schemaModel.js, test/models/schemaModel.js
=> Added filter action to Object and list.

css/sass/main.scss, src/DetailView/DetailView.jsx, src/DetailView/index.js, src/DetailView/index.test.js, src/TableView/TableSelectors.js, src/TableView/TableSelectors.test.js, src/TableView/TableView.jsx, src/components/Detail.jsx, src/components/LoadingIndicator.jsx, src/routes/createRoutes.js
=> Added feature to show child resources.

app/js/views/detailView.js
This commit fixes the issue creating another resource with id:undefined when updating in DetailView.
=> Fix DetailView Update

app/js/models/schemaModel.js
=> Fix issue with resource creation failed for list type with string relation.

app/js/views/breadCrumbView.js, app/js/views/detailView.js
=> Improve BreadCrumb generation in Detail View.

app/css/sass/layout.scss, app/js/models/customActionModel.js, app/js/models/schemaModel.js, app/js/views/customActionsView.js, app/js/views/detailView.js, app/templates/customActions.html, app/templates/detail.html
=> Added custom actions.

css/sass/main.scss, src/app/components/SidebarMenu.jsx, src/app/components/SidebarMenu.test.js
=> Added search bar in sidebar and updated tests.

src/Dialog/Dialog.jsx
=> Added passing UI Schema to Dialog component.

src/Dialog/formComponents/fields/ObjectField.js
=> Added order for object field.

app/js/models/schemaModel.js, app/js/views/dialogView.js, app/js/views/formsEditors/objectEditor.js
ESI-10943
Also i created PR to backbone forms 
https://github.com/powmedia/backbone-forms/pull/542
=> Added order property to object editor.

src/app/components/SidebarSelectors.js, src/app/components/SidebarSelectors.test.js, src/config.json.sample
=> Added feature to create custom buttons to sidebar menu.

src/components/Table/TableRowComponent.jsx, src/components/Table/TableRowComponent.test.js
=> Fixed showing null value.

src/components/Table/Table.jsx, src/components/Table/TableToolbarComponent.jsx
=> Changed new resource button text.

src/TableView/TableView.jsx, src/components/Table/Table.jsx
=> Added confirmation for delete selected rows.

app/js/routers/router.js
=> Fix problem with custom root URL.

src/TableView/TableView.jsx, src/components/Table/Table.jsx, src/components/Table/TableToolbarComponent.jsx, src/components/Table/TableToolbarComponent.test.js
=> Fixed table search.

css/sass/main.scss, src/app/App.jsx, src/app/components/Navbar.jsx, src/app/components/Navbar.test.jsx, src/app/components/SidebarMenu.jsx
=> Added toggling sidebar.

src/TableView/TableView.jsx, src/app/App.jsx, src/error/ErrorToaster.jsx
=> Fixed problems with errorToaster.

src/Dialog/formComponents/fields/ObjectField.js, src/Dialog/formComponents/fields/ObjectField.test.js
=> Added properties logic.

css/sass/main.scss, src/Dialog/formComponents/widgets/BaseInput.js
=> Tweaked dialog errors style.

css/sass/dialog.scss, css/sass/main.scss, src/Dialog/formComponents/widgets/SelectWidget.js, src/Dialog/formComponents/widgets/SelectWidget.test.js
=> Created new select widget with sort feature.

css/sass/dialog.scss, css/sass/main.scss, src/Dialog/formComponents/Label.js, src/Dialog/formComponents/fields/DescriptionField.js, src/Dialog/formComponents/fields/ObjectField.js, src/Dialog/formComponents/fields/TitleField.js, src/Dialog/formComponents/widgets/BaseInput.js, src/Dialog/formComponents/widgets/CheckboxWidget.js
=> Tweaked dialog fields styling.

css/sass/dialog.scss, src/Dialog/formComponents/fields/ObjectField.js, src/Dialog/formComponents/fields/TitleField.js, src/Dialog/formComponents/fields/TitleField.test.js
=> Added showing/hiding object's children.

app/js/models/userModel.js
=> Fix not working transfer storage issue.

css/sass/dialog.scss, package.json, src/Dialog/formComponents/fields/ArrayField/ArrayField.js
=> Tweaked array style and updated BlueprintJS.

src/app/components/SidebarMenu.jsx, src/app/components/SidebarMenu.test.js
=> Fix sidebar selected item highlight.

app/templates/detail.html, app/templates/table.html
=> Support for permissions property in schema.

app/js/models/userModel.js
=> Fixed session transfer.

src/app/components/Navbar.jsx
=> Fixed issue with change tenant from top bar.

src/Dialog/Dialog.jsx
=> Fixed dialog title bugs.

src/Dialog/DialogAction.test.js, src/Dialog/DialogActions.js, src/Dialog/formComponents/fields/ArrayField/ArrayField.js, src/Dialog/formComponents/fields/ObjectField.js, src/Dialog/formComponents/fields/TitleField.js
=> Added feature to dialogs "Optional object can be deleted."

src/Dialog/Dialog.jsx
=> Added custom title for dialog.

locales/en-us/uiSchema.json.sample, src/DetailView/DetailView.jsx, src/app/reducers.js, src/index.js, src/uiSchema/UiSchemaAction.test.js, src/uiSchema/UiSchemaActionTypes.js, src/uiSchema/UiSchemaActions.js, src/uiSchema/UiSchemaSelectors.js, src/uiSchema/UiSchemaSelectors.test.js, src/uiSchema/uiSchemaReducer.js, src/uiSchema/uiSchemaReducer.test.js, uiSchema.md, webpack.config.js
=> Added fetch UI:schema and apply it to detail dialog.

src/TableView/TableActions.js
There were two cases that needed to be handled:
- deleting one item using the trash can icon (when it is last)
- deleting multiple items using checkboxes
=> Fixed the bug with deleting last page of data in a table

src/Dialog/formComponents/widgets/CheckboxWidget.js, src/components/Detail.jsx, src/components/Table/TableRowComponent.jsx
as a bonus, boolean fields are displayed correctly in table and detail view
=> Fixed boolean fields default value (issue #325).

css/sass/dialog.scss
=> Added scroll to dialogs.

css/sass/dialog.scss, src/Dialog/formComponents/fields/ArrayField/ArrayField.js
=> Changed array of objects dialog view.

css/sass/main.scss, src/app/components/Sidebar/Sidebar.jsx, src/app/components/Sidebar/Sidebar.test.js, src/app/components/Sidebar/SidebarSelectors.js, src/app/components/Sidebar/SidebarSelectors.test.js, src/app/components/Sidebar/components/MenuCategory.jsx, src/config.json.sample
=> Added categories and favorites to sidebar.

src/app/components/Navbar/Navbar.jsx, src/app/components/Navbar/components/TenantMenuItem.jsx, src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js, src/auth/AuthEpics.test.js, src/auth/AuthSelectors.js, src/auth/components/SelectTenant.jsx, src/auth/components/SelectTenant.test.jsx, src/config.json.sample
ESI-13956
Possible Keystone versions in `config.json`:
```
"keystoneVersion": "v2" | "v3"
```
Fallback to Keystone V2 when no `keystoneVersion` option provided.
=> Added Keystone V3 support.

src/auth/AuthEpics.js, src/auth/AuthEpics.test.js, src/config.json.sample
Now:
* to use v3 keystone api user need add `/v3` suffix to `authUrl`
* to use v2 keystone api user need add `/v2.0` suffix to `authUrl`
=> Changed conditions for keystone versions.

src/Dialog/formComponents/fields/ArrayField/ArrayField.js, src/components/forms/Select/Select.js
=> Added feature multi select for select component.

css/sass/dialog.scss, src/Dialog/formComponents/fields/ArrayField/ArrayField.js
Tweak to look similar to v1 layout
=> Tweak form css

css/sass/main.scss
=> Fixed not working scroll in codeeditor.

src/Dialog/DialogAction.test.js, src/Dialog/formComponents/widgets/SelectWidget.js, src/components/forms/Select/Select.js, src/components/forms/Select/select.css, src/schema/SchemaActions.js
=> Fix select behavior for null value.

src/Dialog/formComponents/fields/ObjectField.js
=> Fixed displaying dialog when there is no schema property title.

css/sass/main.scss, src/components/Table/index.js
=> Added detail link icon to tableView row options.

src/DetailView/DetailEpics.js, src/config.json.sample
=> Replaced hardcoded pollingInterval to the one from config.json in DetailEpics.

src/TableView/TableComponent.js
=> Fixed prop types for table headers.

src/CustomActions/CustomActions.jsx, src/CustomActions/CustomActionsSuccessToaster.jsx, src/components/SuccessToaster.jsx
=> Fixed not showing success toaster for custom action.

src/Dialog/Dialog.jsx, src/Dialog/formComponents/widgets/BaseInput.js
Fixed integer field.
ESI-16110
=> Added workaround to block global validation of dialogs.

src/Dialog/Dialog.jsx
=> Fix sending empty objects and nulls in arrays.

src/components/Table/index.js
=> Fix table view error with showing with array of types.

package-lock.json, package.json, src/CustomActions/CustomActions.jsx, src/CustomActions/CustomActionsSelectors.js, src/CustomActions/CustomActionsSuccessToaster.jsx, src/CustomActions/CustomActipnsSelectors.test.js, src/components/SuccessToaster.jsx
=> Changed format of custom action result to json.

src/Dialog/formComponents/validator/cidrFormat.js, src/Dialog/formComponents/validator/cidrFormat.test.js
=> Fixed cidr validation for ipv4 0.0.0.0/0 and ipv6 ::/0

src/Dialog/formComponents/fields/ObjectField.js
=> Fixed unable edit object resources.

src/Dialog/Dialog.jsx, src/Dialog/formComponents/fields/ObjectField.js, src/Dialog/formComponents/widgets/CodeWidget.jsx, src/Dialog/utils.js, src/schema/SchemaActions.js
=> Fixed object without properties issue.

css/sass/main.scss, src/app/components/Sidebar/Sidebar.jsx, src/app/components/Sidebar/components/Menu.jsx, src/app/components/Sidebar/components/MenuItem.jsx
=> Improved sidebar to show search results without categories.

src/NotFoundView/NotFound.jsx, src/NotFoundView/NotFound.test.jsx, src/SampleView/Sample.jsx, src/breadcrumb/Breadcrumb.jsx, src/breadcrumb/breadcrumbActionTypes.js, src/breadcrumb/breadcrumbActions.js, src/breadcrumb/breadcrumbEpics.js, src/breadcrumb/breadcrumbReducer.js, src/breadcrumb/breadcrumbSelectors.js
=> Added changing document title.

src/Dialog/formComponents/fields/ObjectField.js
=> Fixed wrong behavior when object has null value or is nullable.

src/TableView/TableSelectors.js, src/components/Table/index.js
=> Fix relation property view in table view.

src/Dialog/formComponents/fields/StringField.js
=> Fixed stringField behavior for format text.

src/TableView/TableComponent.js, src/TableView/TableView.jsx
=> Fixed doesn't working selected resource deletion.

src/Dialog/formComponents/validator/index.js
=> Changed version of json-schema in validator from v6 to v4.

src/TableView/TableEpics.js
=> Fixed not working polling.

src/DetailView/DetailEpics.js
=> Fixed fetch related item when is null.

src/TableView/TableSelectors.js, src/TableView/TableSelectors.test.js
=> Fixed returned values getLimit and getActivePage selectors.

src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js
=> Fixed renewing token after switching tenant.

src/DetailView/DetailEpics.js, src/DetailView/DetailEpics.test.js, src/DetailView/DetailView.jsx, src/components/Detail.jsx, src/config.json.sample, src/config/ConfigSelectors.js, src/config/ConfigSelectors.test.js
=> Added followable relations configuration via config file.

src/TableView/TableView.jsx
=> Fix delete selected error.

src/TableView/TableSelectors.js
=> Fixed doesn't work in view property in Tableview.

src/CustomActions/CustomActions.jsx, src/Dialog/Dialog.jsx
=> Changed form submit button label to create/update.

css/sass/main.scss, src/TableView/TableView.jsx, src/TableView/tableReducer.js, src/TableView/tableReducer.test.js, src/components/Table/CellComponents/InputCheckRow.jsx, src/components/Table/TableRow.jsx, src/components/Table/index.js
Added deletion animation.
ESI-16561
=> Fixed 'select all' behavior after deleting.

src/schema/SchemaActions.js
=> Fixed empty label name for options.

src/NotFoundView/NotFound.jsx, src/SampleView/Sample.jsx, src/breadcrumb/Breadcrumb.jsx, src/breadcrumb/breadcrumbSelectors.js
=> Fixed breadcrumb and title for sampleView and NotFoundView.

src/components/Table/index.js
=> Fixed crashing table view when no item in response.

src/components/forms/Select/Select.js
=> Changed search in select component to case insensitive.

src/DetailView/DetailView.jsx, src/TableView/TableComponent.js, src/components/Detail.jsx, src/components/Table/TableToolbar.jsx, src/components/Table/TableToolbar.test.js
=> Added checking permissions in detailView and table toolbar.

src/TableView/TableSelectors.js, src/components/Table/index.js
=> Fixed sorting by key in table.

src/index.js
=> Fixed showing active sidebar menu item.

src/auth/AuthActions.js, src/auth/AuthEpics.js
=> Added renewing token with password for Keystone 3.

src/auth/AuthActions.js, src/auth/AuthEpics.js
Reverts cloudwan/gohan_webui#425
=> Revert "Added renewing token with password for Keystone 3."

css/main.scss
=> Fixed displaying text in code widget inside dialog.

src/Dialog/DialogSelectors.js, src/Dialog/DialogSelectors.test.js
=> Added opened dialog selectors.

src/TableView/TableView.jsx
=> Fixed not working filter in child view.

src/Dialog/Dialog.jsx, src/Dialog/utils.js
=> Fixed nullable behavior for empty object

package-lock.json, src/Dialog/Dialog.jsx
=> Fixed not setting default values in form data.

src/Dialog/Dialog.jsx, src/Dialog/utils.js
This reverts commit 0a97a7777e598f4955e414f8129e920072feb069.
=> Revert "Fixed nullable behavior for empty object."

src/schema/SchemaSelectors.js, src/schema/SchemaSelectors.test.js
=> Fix collection resources url's

src/DetailView/DetailView.jsx, src/TableView/TableView.jsx, src/TableView/TableView.test.js
=> Fixed blinking dialogs.

src/Dialog/Dialog.jsx, src/Dialog/DialogActions.js, src/schema/SchemaActions.js
=> Added ui:query to fetch related data.

src/uiSchema/UiSchemaAction.test.js, src/uiSchema/UiSchemaActions.js
=> Fixed path to uiSchema.json file.

src/schema/SchemaActions.js, src/schema/SchemaSelectors.js
=> Added option for setting custom labels in dialog fields.

src/Dialog/formComponents/widgets/CodeWidget.jsx
=> Fixed text display in CodeEditor.

src/components/Detail.jsx
=> Fix YAML format view in detailview

src/Dialog/Dialog.jsx, src/schema/SchemaActions.js
=> Used lodash merge for uiSchema and jsonUiSchema in Dialog.

src/schema/SchemaActions.js, src/schema/SchemaSelectors.js, src/schema/SchemaSelectors.test.js
=> Added removing undefined from url in getSingular api method.

src/schema/SchemaAction.test.js, src/schema/SchemaActions.js
=> Improved parsing custom label template inside dialog.

src/Dialog/formComponents/fields/StringField.js, src/Dialog/formComponents/widgets/SelectWidget.js
=> Disabled sorting of enum lists in SelectWidget.

src/Dialog/formComponents/fields/ObjectField.js
UIE-248
Examples:
* Path Selection Profile
* WAN Profile
=> Fixed object type properties order.

src/Dialog/utils.js
=> Modified Dialog utils removeEmpty method to not filter out empty arrays.

src/Dialog/Dialog.jsx, src/Dialog/formComponents/fields/ArrayField/ArrayField.js, src/Dialog/formComponents/fields/ObjectField.js
UIE-247
* Array property:
* Array property required:
* Object property:
* Object property required:
=> Fixed form display behavior for required property.

src/DetailView/DetailView.jsx, src/TableView/TableView.jsx
=> Added removed item name or id to delete dialog message.

src/components/Table/index.js
=> Fixed displaying table cell while data is empty array.

src/Dialog/utils.js
=> Fix nullable object field.

src/DetailView/DetailEpics.js, src/DetailView/DetailEpics.test.js, src/DetailView/DetailSelectors.js, src/DetailView/DetailSelectors.test.js, test/helpers/expectFuctionReturnObservable.js
=> Fixed relation property links creating.

css/main.scss, src/Dialog/Dialog.jsx
=> Added message to dialog without configurable parameters.

src/Dialog/formComponents/widgets/BaseInput.js
=> Fixed Dialog number field validation for decimal numbers ending with 0.

src/schema/SchemaActions.js
=> Fixed dialogs when dialog property relation is null.

package-lock.json, package.json, src/api/index.js, src/schema/SchemaSelectors.js, src/schema/SchemaSelectors.test.js
=> Fix tenant filtering for tenant independent resources.

src/TableView/TableSelectors.js, src/components/Table/ToolbarComponents/Filter.jsx, src/components/Table/index.js
=> Fixed table filter for relation property.

src/schema/SchemaActions.js
=> Fix issue with limit:0 from toLocalSchema.

src/components/forms/Select/Select.js
=> Fixed showing null in Select component when there is no item selected.

src/Dialog/DialogAction.test.js, src/schema/SchemaActions.js
=> Fixed fetching relation resources with no permissions.

src/Dialog/formComponents/fields/ObjectField.js
=> Added support for null value in uiSchema hide logic.

src/Dialog/formComponents/fields/StringField.js, src/Dialog/formComponents/widgets/BaseInput.js, src/components/forms/Input.js
=> Added ui:step property support to uiSchema.

webpack.config.js
=> Fixed gohan version global variable.

src/DetailView/DetailView.jsx, src/TableView/TableComponent.js, src/TableView/TableView.jsx, src/components/Detail.jsx, src/components/Table/TableToolbar.jsx, src/schema/SchemaSelectors.js, src/schema/SchemaSelectors.test.js
=> Displayed actions  specific to view (detail/table).

src/Dialog/formComponents/widgets/index.js
=> Add widget mapping for ipv4 network and ipv4 address with cidr.

src/Dialog/formComponents/widgets/index.js
=> Add widget mapping for version format.

locales/en-us/uiSchema.json, src/Dialog/formComponents/SchemaHint.jsx, src/Dialog/formComponents/fields/YamlField.js, src/Dialog/formComponents/fields/index.js, src/Dialog/formComponents/utils.js, src/components/forms/Error.js
=> Yaml widget.

src/auth/Auth.jsx, src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js, src/auth/AuthEpics.test.js, src/auth/components/Login.jsx, src/config.json.sample, src/config/ConfigSelectors.js, src/config/ConfigSelectors.test.js
=> Add domain support to auth process .

src/Dialog/formComponents/fields/NumberField.js, src/Dialog/formComponents/widgets/BaseInput.js
=> Fixed setting null for properties with types integer/number and null.

src/SuccessToaster/SuccessToaster.jsx, src/SuccessToaster/SuccessToasterSelectors.js, src/SuccessToaster/SuccessToasterSelectors.test.js
=> Fixed showing success toaster while toaster data is empty object.

.github/CODEOWNERS
Add codeowners file with specified owners
Better handling reviews
=> Add codeowners for better reviewers handling.

src/Dialog/formComponents/fields/ObjectField.js
Added if statment for nullable object in ObjectField.
Missing feature in our code.
=> Fix support of nullable objects tabs. [UIE-383]

src/auth/AuthActions.js
CW-877
Added passing non-null token to the Keystone request.
Bug fix.
=> Fixed passing null token.

package-lock.json, package.json
* Add field `ui:title` to change title in dialog using uiSchema. [UIE-409]
* Fix not working "ui:widget": "hidden" for object, array and string types. [CW-882]
* Fixed passing null token.
=> Release 2.29.0

src/auth/AuthEpics.js
CW-877
Renewal auth token by providing password in dialog was added.
CW-877
=> Added showing token renewal dialog.

package.json
* Added showing token renewal dialog. CW-877
=> Release 2.30.0

css/main.scss, src/CustomActions/CustomActions.jsx, src/CustomActions/CustomActionsActions.js, src/CustomActions/CustomActionsActions.test.js, src/CustomActions/CustomActionsEpics.js, src/CustomActions/CustomActionsEpics.test.js, src/SuccessToaster/SuccessToaster.jsx, src/SuccessToaster/SuccessToasterReducer.js, src/SuccessToaster/SuccessToasterReducer.test.js, src/SuccessToaster/SuccessToasterSelectors.js, src/api/index.js, src/components/IFrame.jsx
UIE-405
Modified Custom Action to handle requests (redirects) that return html 
=> Added IFrame component to display HTML response from redirected request.

package-lock.json, src/Dialog/formComponents/validator/index.js, src/Dialog/formComponents/validator/versionConstraintFormat.js, src/Dialog/formComponents/validator/versionConstraintFormat.test.js, src/Dialog/formComponents/widgets/index.js
UIE-412
Added version constraint validator and attached it into Ajv.
Registered widget for `version-constraint` format.
Gohan introduces new format `version-constraint` for handling constrainted semantic version.
=> Added handling version constraint in forms.

package-lock.json, package.json
* Added IFrame component to display HTML response from redirected request. UIE-405
* Added handling version constraint format. UIE-412
=> Release 2.31.0

package-lock.json, package.json
* Fixed displaying ids instead of names in MultiSelect. CW-947
Upgraded gohan_webui version to 2.31.1.
Fix for MultiSelect field in forms.
=> Release 2.31.1

package-lock.json, package.json
* Added Keystone Domain support. [UIE-413]
=> Release 2.32.0

package-lock.json, package.json
Updated `gohan-webui` version to 2.32.1.
Release of the new version.
=> Release 2.32.1

package-lock.json, package.json
* Fixed closing dialog on click outside of the dialog window. [CW-1037]
The release of the new version.
=> Release 2.32.2

css/console.scss, css/main.scss, package-lock.json, package.json, src/CustomActions/CustomActions.jsx, src/CustomActions/CustomActionsActions.js, src/CustomActions/CustomActionsActions.test.js, src/CustomActions/CustomActionsEpics.js, src/CustomActions/CustomActionsEpics.test.js, src/SuccessToaster/SuccessToaster.jsx, src/SuccessToaster/SuccessToasterReducer.js, src/SuccessToaster/SuccessToasterReducer.test.js, src/SuccessToaster/SuccessToasterSelectors.js, src/SuccessToaster/SuccessToasterSelectors.test.js, src/SuccessToaster/components/ToasterContent.jsx, src/SuccessToaster/components/ToasterMessage.jsx, src/SuccessToaster/components/WebSocketTerminal.jsx, src/SuccessToaster/components/index.js, src/api/index.js, src/api/index.test.js, src/components/Console.jsx
UIE-420
- added handling new response format for custom actions.
- added WebSocket factory function
- refactoring of custom actions.
Support real time communication for custom actions.
=> Changed custom actions to support WebSockets.

package-lock.json, package.json
- Added support of WebSockets for Custom Actions. UIE-420
=> Release 2.33.0

src/components/Table/TablePagination.jsx
- added passing additional properties to ReactPaginate component
Support page change from location query.
Support passing `forcePage` to ReactPaginate component.
=> Added passing additional properties to React Paginate component.

package-lock.json, package.json
Release 2.33.1:
* Added passing additional properties to React Paginate component.
=> Release 2.33.1

src/auth/requestAuth.jsx
UIE-445
Added one optional parameter to requestAuth method.
=> Fix missing possibility to change auth component in requestAuth method

package-lock.json, package.json
* Fixed changing tenant filter on reload and handling renew token error. [UIE-431]
=> Release 2.33.3

src/SuccessToaster/SuccessToaster.jsx, src/SuccessToaster/components/ToasterContent.jsx, src/SuccessToaster/components/WebSocketTerminal.jsx, src/auth/Auth.jsx, src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js, src/auth/AuthSelectors.js, src/config/ConfigSelectors.js
UIE-452
Added prefixing for items saved in session storage.
Disable sharing the same token by admin and tenant UI.
=> Fixed adding prefix to items saved in session storage.

src/app/components/Navbar/Navbar.jsx
The condition for showing tenant filter has been extended. 
Hide tenant filter for a single tenant.
=> Fixed showing tenant filter for single tenant.

package-lock.json, package.json
Included commits:
* Fixed showing tenant filter for single tenant.
* Fixed adding prefix to items saved in session storage. [UIE-452]
Upgraded version of gohan-webui.
The release of the new version.
=> Release 2.33.4

src/SuccessToaster/SuccessToaster.jsx, src/SuccessToaster/components/ToasterContent.jsx, src/SuccessToaster/components/WebSocketTerminal.jsx
changed token from session storage to redux selector
Issue
=> Fix update token in cookie for web socket.

src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js, src/auth/AuthEpics.test.js, src/auth/authReducer.js, src/auth/authReducer.test.js
fix missing logout after token expired, fix token renewal dialog after reload.
issue
=> Fix renew token and logout.

package-lock.json, package.json
Release 2.33.5
* Fix renew token and logout. [CW-1246]
* Fix update token in cookie for web socket. [CW-1262]
=> Release 2.33.5

src/SuccessToaster/SuccessToaster.jsx, src/SuccessToaster/components/ToasterContent.jsx, src/components/IFrame.jsx
Fixed typo, add cookit to iframe
issue
=> Add cookie to iframe.

package.json
Release 2.33.6
* Fix updating the cookie Auth token for custom actions [CW-1262]
=> Release 2.33.6

src/auth/AuthEpics.js
UIE-490
Fixed login for project admin.
Fixed login for project admin.
=> [UIE-490] Fixed login for project admin.

package-lock.json, package.json
* Fixed login for project admin. [UIE-490]
=> Release 2.33.7

src/auth/Auth.jsx, src/auth/AuthActions.js, src/auth/AuthEpics.js, src/routes/Routes.js
To do this user should add to url query like `?token=<token_id>`
=> [UIE-496] Add login by token to ui.

package-lock.json, package.json
* Add login by token to ui. [UIE496]
=> Release 2.34.0

src/config.json.sample, src/config/ConfigActions.js
insert 1st gtoup from regex as domain name.
Task
=> [UIE-497] Add posibility to set domainName based on regex.

package-lock.json, package.json
* Add posibility to set domainName based on regex. [UIE-497]
=> Release 2.35.0

src/TableView/TableActions.js, src/TableView/TableActions.test.js, src/TableView/TableEpics.js, src/TableView/TableView.jsx, src/components/Table/TablePagination.jsx
UIE-457
Fixed changing table page after deleting last resource on the table subpage.
Table page shows empty table after deleting last table resource of the table subpage, despite the fact that table has data.
=> Fixed changing table page after deleting last item.

package-lock.json, package.json
* Fixed changing table page after deleting last item. [UIE-457]
=> Release 2.35.1

src/DetailView/DetailView.jsx, src/TableView/TableView.jsx, src/TableView/TableView.test.js
UIE-449
Added refetching resources in `TableView` and `DetailView` after tenant filter change.
After tenant filter change, it was necessary to change or reload page to see new (filtered) resources.
=> Added refetching resources after tenant change.

package-lock.json, package.json
* Added refetching resources after tenant change. [UIE-449]
=> Release 2.36.0

src/TableView/TableComponent.js, src/TableView/TableEpics.js, src/TableView/TableView.jsx, src/components/Table/TableToolbar.jsx
UIE-519
Added searching substrings in TableView.
Changed approach to keep the filter query in location bar.
Added filtering filters by type `string`.
Support searching substrings.
=> Added support of substring searching.

package-lock.json, package.json
* Added support of substring search. [UIE-519]
=> Release 2.37.0

src/TableView/TableSelectors.js, src/TableView/TableSelectors.test.js, src/components/Table/TableToolbar.jsx
UIE-519
- added removing filters with relation (change in table's selector)
Support substring searching.
=> Added removing filters with relation.

package-lock.json, package.json
* Added removing filters with relation. [UIE-519]
=> Release 2.37.1

package-lock.json, package.json
UIE-523
Updated axios  to `0.19.0`
Security issues.
=> Updated axios.

package-lock.json, package.json
=> Release 2.37.2

src/DetailView/DetailActionTypes.js, src/DetailView/DetailActions.js, src/DetailView/DetailEpics.js
UIE-524
* Fixed detail fetch when property has relation without schema.
* UI rendering stops and shows only loaders when got schema ref error.
=> Fixed detail fetch when property has relation without schema.

package-lock.json, package.json
* Added support of is_public and any_of. [UIE-518]
* Fixed detail fetch when property has relation without schema. [UIE-524]
=> Release 2.38.0

README.md, src/app/components/Sidebar/SidebarSelectors.js, src/app/components/Sidebar/SidebarSelectors.test.js, src/config.json.sample, src/config/ConfigSelectors.js, src/config/ConfigSelectors.test.js, src/routes/createRoutes.js
UIE-526
- added entry `sidebarChildResources` in config
- added routes for child resources
- added showing child resources in sidebar menu
Support child resources in sidebar menu.
=> Added support showing child resources in sidebar menu.

README.md, src/routes/createRoutes.js
Add to create routes possibility to disable match path exactly.
This feature is needed for more user-friendly routing.
=> Add to create routes possibility to disable match path exactly.

package-lock.json, package.json
* Added support showing child resources in sidebar menu. [UIE-526]
* Add to create routes possibility to disable match path exactly.
* Added support of toggling substring search. [UIE-527]
* Add possibility to pass props to open dialog.
* Fixed getSidebarItems for no sidebarChildResources.
=> Release 2.39.0

src/Form/Form.jsx
UIE-540
Added `shouldComponentUpdate` method.
Resetting inline forms when parent got updated props.
=> Fixed form resetting.

src/Dialog/Dialog.jsx
Missing props pass to Form component from dialog.
Unable to pass uiSchema to form component.
=> UIE-556 UIE-554 Fix missing uiSchema pass to form.

package-lock.json, package.json
* Fix missing uiSchema pass to form. [UIE-556][UIE-554]
* Fixed form resetting. [UIE-540]
* Added Form component and utils.
=> Release 2.40.0

package-lock.json, package.json
* Add option to trigger preperSchema action silently. [UIE-556]
=> Release 2.40.1

package-lock.json, package.json
* Fix refresh dialog after change schema [UIE-556]
=> Release 2.40.2

.github/workflows/prCheck.yml
Add the first draft of action using new GitHub action feature.
=> Update and rename nodejs.yml to prCheck.yml

src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js, src/auth/AuthEpics.test.js, src/auth/authReducer.js, src/auth/authReducer.test.js, src/config.json.sample
=> [CW-1613] Changed Cloud Admin detection.

package-lock.json, package.json
* Changed Cloud Admin detection.[CW-1613]
=> Release 2.41.0

.github/CODEOWNERS, README.md, src/config.json.sample
Add info about config json and ui schema
Missing some information in readme
=> UIE-563 Updated readme.md

src/TableView/TableComponent.js, src/components/Table/index.js
Added `urlTemplate` prop to table component.
Some custom table views require some way to use custom url to detail pages.
=> [UIE-559] Added urlTemplate prop to table component.

package-lock.json, package.json
* Added urlTemplate prop to table component.
* Updated readme.md
Upgraded gohan_webui version.
Release 2.42.0
=> Release 2.42.0

package.json, src/SuccessToaster/components/WebSocketTerminal.jsx, src/SuccessToaster/components/WebSocketTerminal.test.js, src/api/index.js, test/helpers/dom.js
Add missing removing cookie after closing success toaster.
Ticket CW-1927
=> [CW-1927] Fix removing cookie after close success toaster.

package-lock.json, package.json
* Fix removing cookie after close success toaster. [CW-1927]
=> Release 2.42.1

src/schema/SchemaAction.test.js, src/schema/SchemaActions.js
Added support of removal deprecated properties in schema.
Stop support of deprecated properties in schema.
=> Added ignoring of deprecated resources in schema.

package-lock.json, package.json
* Added ignoring of deprecated resources in schema
*  Fixed lack of change of package version in package.json
=> Release 2.42.3

css/form.scss, locales/en-us/uiSchema.json, package-lock.json, src/Form/formComponents/fields/ArrayField/ArrayField.js, src/Form/formComponents/fields/StringField.js, src/Form/formComponents/widgets/SelectWidget.js, src/components/forms/Select/Select.js
Added support for `enumDisabled` `uiSchema` option in `SelectWidget` and `ArrayField`.
UI should disable reserved tags.
=> [CW-3646] Added support for enumDisabled uiSchema option in SelectWidget and ArrayField.

package-lock.json, package.json
* Changed gohan_webui version to 2.42.4
* New version release
=> Release 2.42.4

package-lock.json, package.json
Updated Gohan version to 2.42.5
* [CW-3836] Fixed height and sorting of tenant select.
Release
=> Release 2.42.5

src/auth/AuthEpics.js
Changed getting the current date for calculating timeout based on the token expiry date.
* Previous solution: Current date was set by `moment()` which resulted in immediate log out when a user had the date and time setting not synced with the selected timezone.
* Current solution: Current date is set based on response header `Date`, so it's independent of a user system settings.
* Before fix:
* After fix:
Some users experienced immediate log out after log in because a timeout was calculated incorrectly.
=> [CW-3893] Fixed immediate logout caused by wrong token expiration timeout.

package-lock.json, package.json
* [CW-3893] Fixed immediate logout caused by wrong token expiration timeout.
Release new version
=> Release 2.42.6

src/auth/AuthActions.js, src/auth/AuthActions.test.js, src/auth/AuthEpics.js, src/auth/components/Login.jsx, src/auth/components/Login.test.jsx, src/auth/components/TokenRenewal.jsx
=> Added MFA support.

package-lock.json, package.json
* [CW-4286] Added MFA support to login.
* [CW-4291] Added MFA support to Token Renewal.
Gohan release.
[CW-4286]: https://cloudwan.atlassian.net/browse/CW-4286
[CW-4291]: https://cloudwan.atlassian.net/browse/CW-4291
=> Release 2.43.0
